# Source: firehose-exporter
---
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/custom_rules?/-
  value:
    name: DiegoCellRepMemoryCapacity
    rules:
      - record: rep_memory_capacity_pct:avg5m
        expr: >
          100 *
          sum(avg_over_time(firehose_value_metric_rep_capacity_remaining_memory{environment="((metrics_environment))"}[5m])) by (environment, bosh_job_name) /
          sum(avg_over_time(firehose_value_metric_rep_capacity_total_memory{environment="((metrics_environment))"}[5m])) by (environment, bosh_job_name)
      - alert: DiegoCellRepMemoryCapacity
        expr:  rep_memory_capacity_pct:avg5m < 35
        for: 2h
        labels:
          severity: warning
        annotations:
          summary: Rep low free memory capacity
          description: >
            Low free memory {{ $value | printf "%.0f" }}% for the advertised rep memory capacity
            in the last 2 hours on average.
            Review if we need to scale...
          url: https://team-manual.cloud.service.gov.uk/architecture_decision_records/ADR021-cell-capacity-assignment-2/#decision
