buildpacks:
- name: binary_buildpack
  repo_name: binary-buildpack
  stack: cflinuxfs3
  version: v1.0.36
  sha: 8bf473f805b9e8deff6f58d57533737d6afe02fa3ad6a27073e73e100b2b0937
  filename: binary-buildpack-cflinuxfs3-v1.0.36.zip
  url: https://github.com/cloudfoundry/binary-buildpack/releases/download/v1.0.36/binary-buildpack-cflinuxfs3-v1.0.36.zip
  dependencies: []
- name: dotnet_core_buildpack
  repo_name: dotnet-core-buildpack
  stack: cflinuxfs3
  version: v2.3.18
  sha: 0bafd999bd5c4ac16643109914d7266c1bfaecfdd5601aa2b9dd8a154c159b33
  filename: dotnet-core-buildpack-cflinuxfs3-v2.3.18.zip
  url: https://github.com/cloudfoundry/dotnet-core-buildpack/releases/download/v2.3.18/dotnet-core-buildpack-cflinuxfs3-v2.3.18.zip
  dependencies:
  - name: bower
    version: 1.8.8
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 2.1.22
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 2.1.23
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 3.1.8
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 3.1.9
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 2.1.22
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 2.1.23
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 3.1.8
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 3.1.9
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 2.1.810
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 2.1.811
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 3.1.402
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 3.1.403
    cf_stacks:
    - cflinuxfs3
  - name: libgdiplus
    version: "6.0"
    cf_stacks:
    - cflinuxfs3
  - name: libunwind
    version: 1.4.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 10.23.0
    cf_stacks:
    - cflinuxfs3
- name: go_buildpack
  repo_name: go-buildpack
  stack: cflinuxfs3
  version: v1.9.23
  sha: 394a7f503c80ec184ab6b2baea201c44ec973956667c6b3d666cbcb17d6d87c6
  filename: go-buildpack-cflinuxfs3-v1.9.23.zip
  url: https://github.com/cloudfoundry/go-buildpack/releases/download/v1.9.23/go-buildpack-cflinuxfs3-v1.9.23.zip
  dependencies:
  - name: dep
    version: 0.5.4
    cf_stacks:
    - cflinuxfs3
  - name: glide
    version: 0.13.3
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.14.11
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.14.12
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.15.4
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.15.5
    cf_stacks:
    - cflinuxfs3
  - name: godep
    version: "80"
    cf_stacks:
    - cflinuxfs3
- name: java_buildpack
  repo_name: java-buildpack
  stack: cflinuxfs3
  version: v4.34
  sha: 3eff3bfd1e89c5dc061ebb81ec888617b3b974beccdccc9ef4ac5585565b6bad
  filename: java-buildpack-v4.34.zip
  url: https://github.com/cloudfoundry/java-buildpack/releases/download/v4.34/java-buildpack-v4.34.zip
  dependencies: []
- name: nodejs_buildpack
  repo_name: nodejs-buildpack
  stack: cflinuxfs3
  version: v1.7.36
  sha: eacb011c666461be423020751d8ce7e1a4c5111b7214ed54ab05c8a9acd49a98
  filename: nodejs-buildpack-cflinuxfs3-v1.7.36.zip
  url: https://github.com/cloudfoundry/nodejs-buildpack/releases/download/v1.7.36/nodejs-buildpack-cflinuxfs3-v1.7.36.zip
  dependencies:
  - name: node
    version: 10.22.1
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 10.23.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 12.19.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 12.19.1
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 14.15.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 14.15.1
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 15.2.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 15.2.1
    cf_stacks:
    - cflinuxfs3
  - name: yarn
    version: 1.22.10
    cf_stacks:
    - cflinuxfs3
- name: php_buildpack
  repo_name: php-buildpack
  stack: cflinuxfs3
  version: v4.4.26
  sha: b0923e755510656ad5318fd0fe2a56d19297f75a568531d7fc82b7707f052014
  filename: php-buildpack-cflinuxfs3-v4.4.26.zip
  url: https://github.com/cloudfoundry/php-buildpack/releases/download/v4.4.26/php-buildpack-cflinuxfs3-v4.4.26.zip
  dependencies:
  - name: CAAPM
    version: 20.11.0
    cf_stacks:
    - cflinuxfs3
  - name: appdynamics
    version: 20.4.0.3759
    cf_stacks:
    - cflinuxfs3
  - name: composer
    version: 2.0.7
    cf_stacks:
    - cflinuxfs3
  - name: httpd
    version: 2.4.46
    cf_stacks:
    - cflinuxfs3
  - name: newrelic
    version: 9.1.0.246
    cf_stacks:
    - cflinuxfs3
  - name: nginx
    version: 1.18.0
    cf_stacks:
    - cflinuxfs3
  - name: nginx
    version: 1.19.4
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.2.33
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.2.34
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.3.23
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.3.24
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.4.11
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.4.12
    cf_stacks:
    - cflinuxfs3
- name: python_buildpack
  repo_name: python-buildpack
  stack: cflinuxfs3
  version: v1.7.26
  sha: 00e9da36c4d55791a010142269c68955fbf2ff8605e0959c7020cdfd89b565f0
  filename: python-buildpack-cflinuxfs3-v1.7.26.zip
  url: https://github.com/cloudfoundry/python-buildpack/releases/download/v1.7.26/python-buildpack-cflinuxfs3-v1.7.26.zip
  dependencies:
  - name: libffi
    version: 3.2.1
    cf_stacks:
    - cflinuxfs3
  - name: libmemcache
    version: 1.0.18
    cf_stacks:
    - cflinuxfs3
  - name: miniconda3
    version: 4.7.12.1
    cf_stacks:
    - cflinuxfs3
  - name: pip-pop
    version: 0.1.5
    cf_stacks:
    - cflinuxfs3
  - name: pipenv
    version: 2020.11.15
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.6.11
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.6.12
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.7.8
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.7.9
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.8.5
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.8.6
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.9.0
    cf_stacks:
    - cflinuxfs3
  - name: setuptools
    version: 50.3.2
    cf_stacks:
    - cflinuxfs3
- name: ruby_buildpack
  repo_name: ruby-buildpack
  stack: cflinuxfs3
  version: v1.8.27
  sha: 112afb19d2a563aac4ff2a6c140cb30aad2d7ee962fd21e493b43934bb34a3a8
  filename: ruby-buildpack-cflinuxfs3-v1.8.27.zip
  url: https://github.com/cloudfoundry/ruby-buildpack/releases/download/v1.8.27/ruby-buildpack-cflinuxfs3-v1.8.27.zip
  dependencies:
  - name: bundler
    version: 1.17.3
    cf_stacks:
    - cflinuxfs3
  - name: bundler
    version: 2.1.4
    cf_stacks:
    - cflinuxfs3
  - name: jruby
    version: 9.1.17.0
    cf_stacks:
    - cflinuxfs3
  - name: jruby
    version: 9.2.13.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 10.23.0
    cf_stacks:
    - cflinuxfs3
  - name: openjdk1.8-latest
    version: 1.8.0
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.5.7
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.5.8
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.6.5
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.6.6
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.7.1
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.7.2
    cf_stacks:
    - cflinuxfs3
  - name: rubygems
    version: 3.1.4
    cf_stacks:
    - cflinuxfs3
  - name: yarn
    version: 1.22.10
    cf_stacks:
    - cflinuxfs3
- name: staticfile_buildpack
  repo_name: staticfile-buildpack
  stack: cflinuxfs3
  version: v1.5.13
  sha: 7f257745afe7d4685ad9dc6597cf693a67748611d157cf706b355cbffe4f2781
  filename: staticfile-buildpack-cflinuxfs3-v1.5.13.zip
  url: https://github.com/cloudfoundry/staticfile-buildpack/releases/download/v1.5.13/staticfile-buildpack-cflinuxfs3-v1.5.13.zip
  dependencies:
  - name: nginx
    version: 1.19.4
    cf_stacks:
    - cflinuxfs3
- name: nginx_buildpack
  repo_name: nginx-buildpack
  stack: cflinuxfs3
  version: v1.1.18
  sha: a8487be6c00afd5ae995b5129f65bbdb9e3b8100820e952836e0a735620bff03
  filename: nginx-buildpack-cflinuxfs3-v1.1.18.zip
  url: https://github.com/cloudfoundry/nginx-buildpack/releases/download/v1.1.18/nginx-buildpack-cflinuxfs3-v1.1.18.zip
  dependencies:
  - name: nginx
    version: 1.18.0
    cf_stacks:
    - cflinuxfs3
  - name: nginx
    version: 1.19.4
    cf_stacks:
    - cflinuxfs3
  - name: openresty
    version: 1.13.6.2
    cf_stacks:
    - cflinuxfs3
  - name: openresty
    version: 1.15.8.3
    cf_stacks:
    - cflinuxfs3
  - name: openresty
    version: 1.17.8.2
    cf_stacks:
    - cflinuxfs3
  - name: openresty
    version: 1.19.3.1
    cf_stacks:
    - cflinuxfs3
- name: r_buildpack
  repo_name: r-buildpack
  stack: cflinuxfs3
  version: v1.1.11
  sha: d963b4b6e08f0eae641f5f3612c6f69b6f79f72453a7519eb19e03cc847f8476
  filename: r-buildpack-cflinuxfs3-v1.1.11.zip
  url: https://github.com/cloudfoundry/r-buildpack/releases/download/v1.1.11/r-buildpack-cflinuxfs3-v1.1.11.zip
  dependencies:
  - name: r
    version: 3.6.2
    cf_stacks:
    - cflinuxfs3
  - name: r
    version: 3.6.3
    cf_stacks:
    - cflinuxfs3
  - name: r
    version: 4.0.2
    cf_stacks:
    - cflinuxfs3
  - name: r
    version: 4.0.3
    cf_stacks:
    - cflinuxfs3
